# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: buildador

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    container: maven:latest
    steps:  
      - name: tem que dar checkout....
        uses: actions/checkout@v2        
      - name: me da dados
        run: env && ls -la && pwd
      - name: Build with Maven
        run: mvn install
      - name: Create a Release
        uses: actions/create-release@v1.1.4
        with:
          # The name of the tag. This should come from the webhook payload, `github.GITHUB_REF` when a user pushes a new tag
          tag_name:  tag. ${{ github.ref }}
          # The name of the release. For example, `Release v1.0.1`
          release_name: Release ${{ github.ref }}
    
